# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


# [[constraint]]
#   name = "cloud.google.com/go"
#   version = "0.17.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.3.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "^1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/daneharrigan/hipchat"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.4.0"

[[constraint]]
  name = "github.com/rusenask/cron"
  version = "1.1.0"

[[constraint]]
  name = "github.com/rusenask/docker-registry-client"
  branch = "master"

[[constraint]]
  name = "github.com/docker/distribution"  
  revision = "6fca8d6e6713acbdf3f9ca40cf6370fc5ee5ee53"  

[[constraint]]
  name = "github.com/tbruyelle/hipchat-go"
  version = "1.2.0"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "0.3.0"

# [[constraint]]
#   name = "google.golang.org/grpc"
#   version = "1.5.0"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

# [[constraint]]
#   name = "k8s.io/client-go"
#   version = "3.0.0-beta.0"


[[constraint]]
  name="k8s.io/client-go"
  version="kubernetes-1.14.2"

[[constraint]]
  name="k8s.io/api"
  version="kubernetes-1.14.2"

[[constraint]]
  name="k8s.io/apimachinery"
  version="kubernetes-1.14.2"

[[override]]
  name="k8s.io/apiextensions-apiserver"
  revision="bf6753f2aa24fe1d69a2abeea1c106042bcf3f5f"

[[override]]
  name="k8s.io/kubernetes"
  revision="66049e3b21efe110454d67df4fa62b08ea79a19b"

[[override]]
  name="k8s.io/cli-runtime"
  revision="17bc0b7fcef59215541144136f75284656a789fb"

[[override]]
  name="github.com/russross/blackfriday"
  revision="300106c228d52c8941d4b3de6054a6062a86dda3"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/ryanuber/go-glob"
  version = "0.1.0"
